name: Deploy on AWS

on:
  workflow_run:
    workflows: ["Sample react CI pipeline / workflow"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js (LTS)
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'

      # 3️⃣ Install dependencies (ROOT)
      - name: Install dependencies
        run: npm install

      # 4️⃣ Install PM2
      - name: Install PM2
        run: npm install -g pm2

      # 5️⃣ Run tests (if present)
      - name: Run tests
        run: npm test --if-present

      # 6️⃣ Deploy with PM2
      - name: Deploy to AWS
        run: |
          pm2 restart shopcart || pm2 start src/index.js --name shopcart
          pm2 save
